
package soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SOAPServer", targetNamespace = "http://server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOAPServer {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculDeliveryFee", targetNamespace = "http://server/", className = "soap.CalculDeliveryFee")
    @ResponseWrapper(localName = "calculDeliveryFeeResponse", targetNamespace = "http://server/", className = "soap.CalculDeliveryFeeResponse")
    @Action(input = "http://server/SOAPServer/calculDeliveryFeeRequest", output = "http://server/SOAPServer/calculDeliveryFeeResponse")
    public double calculDeliveryFee(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
